# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - harry-kart-web-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Adding secret
      run: |
          appinsightKey='azure.application-insights.instrumentation-key='
          appinsightKeyValue= "$appinsightKey"${{secrets.AZURE_APPLICATION_INSIGHTS_INSTRUMENTATION_KEY}}
          echo appinsightKeyValue >> src/main/resources/application.properties
          cat src/main/resources/application.properties
      shell: bash

    - name: Output application.properties
      uses: actions/upload-artifact@v2
      with:
        name: prop-file
        path: '${{github.workspace}}/src/main/resources/application.properties'

